// <auto-generated />
namespace ComputerShop.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _2310 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2310));
        
        string IMigrationMetadata.Id
        {
            get { return "201710232141336_2310"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
