// <auto-generated />
namespace ComputerShop.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1211 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1211));
        
        string IMigrationMetadata.Id
        {
            get { return "201711121811113_1211"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
