// <auto-generated />
namespace ComputerShop.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _3008 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3008));
        
        string IMigrationMetadata.Id
        {
            get { return "201708302049597_3008"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
